# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(max_length=255),
        ),
    ]
